site_name: Enlumox
pages:
  - [index.md, Home]
  - ['developer/modules.md','Developer Documentation', 'Modules']
  - ['developer/devices.md','Developer Documentation', 'Devices']
  - ['developer/errors.md','Developer Documentation', 'Errors']
theme: readthedocs
